sudo: false
cache: bundler
language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
script:
  - bundle exec rubocop --config .rubocop.yml
  - bundle exec rake test
notifications:
  email: false
